---
- name: Fetch next available VMID from Proxmox if not already provided
  uri:
    url: "{{ proxmox_api_url }}/cluster/nextid"
    method: GET
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    return_content: yes
    validate_certs: no  # Adjust for production
  register: next_vmid_response
  when: vm_item.vmid is not defined or vm_item.vmid == ''
  delegate_to: localhost

- name: Set VMID for the current VM if not already provided
  set_fact:
    vms: "{{ vms | map('combine', {'vmid': (vm_item.vmid | default(next_vmid_response.json.data))}) | list }}"
  when: vm_item.vmid is not defined or vm_item.vmid == ''
